/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#aec6ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdbc9",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#321200",
        "on-secondary-fixed": "#002113",
        "on-primary-container": "#f9f9ff",
        "on-secondary-container": "#00734c",
        "inverse-on-surface": "#eff1f4",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-primary": "#aec6ff",
        "surface-container": "#eceef1",
        "outline-variant": "#c2c6d5",
        "primary-container": "#2a6fdb",
        "surface-container-highest": "#e0e3e6",
        "on-primary-fixed": "#001a42",
        "on-surface-variant": "#424753",
        "on-error": "#ffffff",
        "on-tertiary-container": "#fff8f5",
        "tertiary": "#934300",
        "surface-dim": "#d8dadd",
        "on-surface": "#191c1e",
        "surface-container-low": "#f2f4f7",
        "inverse-surface": "#2d3133",
        "secondary-container": "#70fcba",
        "primary": "#0056bb",
        "on-tertiary-fixed-variant": "#753400",
        "secondary-fixed": "#70fcba",
        "background": "#f7f9fc",
        "secondary": "#006c47",
        "surface": "#f7f9fc",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#50de9f",
        "tertiary-fixed-dim": "#ffb68c",
        "primary-fixed": "#d8e2ff",
        "surface-bright": "#f7f9fc",
        "on-primary-fixed-variant": "#004395",
        "surface-container-high": "#e6e8eb",
        "on-secondary-fixed-variant": "#005234",
        "surface-variant": "#e0e3e6",
        "outline": "#727784",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "on-background": "#191c1e",
        "surface-tint": "#005ac3",
        "tertiary-container": "#b95600"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "xxl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
